extras: Update extras/mpvc-installer

diff --git a/extras/mpvc-installer b/extras/mpvc-installer
--- a/extras/mpvc-installer
+++ b/extras/mpvc-installer
@@ -137,18 +137,15 @@ mpvc_uninstall()
 mpvc_check_requirements()
 {
     # attempt at listing packages required by mpvc & extras/ to work
-    command -v "sh"  || echo "$PROGNAME: Error: No sh found. Install to continue"
-    command -v "mpv" || echo "$PROGNAME: Error: No mpv found. Install to continue"
-    command -v "fzf" || echo "$PROGNAME: Error: No fzf found, Install to continue"
-    command -v "awk" || echo "$PROGNAME: Error: No awk found, Install to continue" # gawk ???
-    command -v "sed" || echo "$PROGNAME: Error: No sed found, Install to continue" # gsed ???
-    command -v "socat" || echo "$PROGNAME: Error: No socat found, Install to continue"
+    echo "# Checking required deps:"
+    for cmd in sh mpv fzf awk sed socat; do
+        command -v "$cmd" | sed 's/^/  /' || echo "$PROGNAME: Error: No $cmd found. Install to continue"
+    done
     # recommened, and good to have, but not required
-    command -v "curl" || echo "$PROGNAME: Warning: No curl found, Install to search streaming services"
-    command -v "rlwrap" || echo "$PROGNAME: Warning: No rlwrap, Install to get history, filename & completion support!"
-    command -v "notify-send" || echo "$PROGNAME: Warning: No notify-send, Install to get mpv desktop notifications"
-    command -v "jq" || echo "$PROGNAME: Warning: No jq found, Install to parse JSON"
-    command -v "yt-dlp" || echo "$PROGNAME: Warning: No yt-dlp, Install to get youtube-dl support (*hint: check $PROGNAME config)"
+    echo "# Checking recommended deps:"
+    for cmd in curl rlwrap notify-send jq yt-dlp; do
+        command -v "$cmd" | sed 's/^/  /' || echo "$PROGNAME: Warning: No $cmd found, is recommended, but not required"
+    done
 }
 
 mpvc_check_update()
