extras: Update extras/mpvc-web

diff --git a/extras/mpvc-web b/extras/mpvc-web
--- a/extras/mpvc-web
+++ b/extras/mpvc-web
@@ -21,6 +21,42 @@ PROGINFO="A hack to remotely control mpvc from web # DISCLAIMER * Use at Your Ow
 
 set -euf
 
+mpvc_web_defaults()
+{
+    MPVC=$(command -v mpvc)
+
+    MPVC_WEB_HOST=${MPVC_WEB_HOST:-localhost}
+    MPVC_WEB_PORT=${MPVC_WEB_PORT:-8000}
+    MPVC_WEB_ROOT=${MPVC_WEB_ROOT:-/tmp/mpvc-web/root}
+    MPVC_WEB_HOSTNAME=$(hostname)
+    MPVC_WEB_SSL_PORT=${MPVC_WEB_SSL_PORT:-8443}
+    MPVC_WEB_SSL_PEM=$MPVC_WEB_ROOT/../stunnel.pem
+    MPVC_WEB_SSL_CFG=$MPVC_WEB_ROOT/../stunnel.cfg
+    MPVC_WEB_SSL_PID=$MPVC_WEB_ROOT/../stunnel.pid
+    MPVC_WEB_SSL_ENABLE=${MPVC_WEB_SSL_ENABLE:-}
+    MPVC_WEB_SSL_VERIFY=${MPVC_WEB_SSL_VERIFY:-0}
+    MPVC_WEB_ARCHIVE_ENABLE=${MPVC_WEB_ARCHIVE_ENABLE:-}
+
+    MPVC_CGI="$MPVC_WEB_ROOT/cgi-bin/mpvc"
+}
+
+mpvc_web_config()
+{
+    mpvc_web_defaults
+
+    if ! command -v python3 >/dev/null; then
+        echo "$PROGNAME: Error: No python3 found, install to continue."
+        exit
+    fi
+    if ! command -v mpvc >/dev/null; then
+        echo "$PROGNAME: Error: No mpvc found, install to continue."
+        exit
+    fi
+    if ! command -v stunnel >/dev/null; then
+        echo "$PROGNAME: Warning: No stunnel found, install to support SSL."
+    fi
+}
+
 mpvc_web_style()
 {
     echo 'body { filter: invert(0.7); }'
@@ -282,42 +318,6 @@ cafile = ${MPVC_WEB_SSL_PEM}
 verify=$MPVC_WEB_SSL_VERIFY
 TIMEOUTclose = 0
 EOF
-}
-
-mpvc_web_defaults()
-{
-    MPVC=$(command -v mpvc)
-
-    MPVC_WEB_HOST=${MPVC_WEB_HOST:-localhost}
-    MPVC_WEB_PORT=${MPVC_WEB_PORT:-8000}
-    MPVC_WEB_ROOT=${MPVC_WEB_ROOT:-/tmp/mpvc-web/root}
-    MPVC_WEB_HOSTNAME=$(hostname)
-    MPVC_WEB_SSL_PORT=${MPVC_WEB_SSL_PORT:-8443}
-    MPVC_WEB_SSL_PEM=$MPVC_WEB_ROOT/../stunnel.pem
-    MPVC_WEB_SSL_CFG=$MPVC_WEB_ROOT/../stunnel.cfg
-    MPVC_WEB_SSL_PID=$MPVC_WEB_ROOT/../stunnel.pid
-    MPVC_WEB_SSL_ENABLE=${MPVC_WEB_SSL_ENABLE:-}
-    MPVC_WEB_SSL_VERIFY=${MPVC_WEB_SSL_VERIFY:-0}
-    MPVC_WEB_ARCHIVE_ENABLE=${MPVC_WEB_ARCHIVE_ENABLE:-}
-
-    MPVC_CGI="$MPVC_WEB_ROOT/cgi-bin/mpvc"
-}
-
-mpvc_web_config()
-{
-    mpvc_web_defaults
-
-    if ! command -v python3 >/dev/null; then
-        echo "$PROGNAME: Error: No python3 found, install to continue."
-        exit
-    fi
-    if ! command -v mpvc >/dev/null; then
-        echo "$PROGNAME: Error: No mpvc found, install to continue."
-        exit
-    fi
-    if ! command -v stunnel >/dev/null; then
-        echo "$PROGNAME: Warning: No stunnel found, install to support SSL."
-    fi
 }
 
 mpvc_web()
