extras: Update extras/mpvc-installer

diff --git a/extras/mpvc-installer b/extras/mpvc-installer
--- a/extras/mpvc-installer
+++ b/extras/mpvc-installer
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env sh
 #
 # @file mpvc-installer
 # @version v1.0
@@ -116,6 +116,7 @@ mpvc_uninstall()
 mpvc_check_requirements()
 {
     # attempt at listing packages required by mpvc & extras/ to work
+    command -v "sh" || echo "$PROGNAME: Error: No sh(1) found. Install to continue."
     command -v "mpv" || echo "$PROGNAME: Error: No mpv found. Install to continue."
     command -v "fzf" || echo "$PROGNAME: Error: No fzf found, Install to continue"
     command -v "awk" || echo "$PROGNAME: Error: No awk found, Install to continue" # gawk ???
